package storage

import (
	"html/template"
)

var indexHTML = template.Must(template.New("index").Parse(`<!doctype html>
<html>
<head>
<meta charset=utf-8>
<meta name=viewport content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css">
<title>Work Presence</title>
</head>
<body onload="main();">
  <ul id="bucket-content"></ul>
  <p style="font-size:smaller; text-align: right;">
    Generated by <a href="https://github.com/jtolio/workpresence">Work Presence</a>.<br/>
    This page is served from <a href="?wrap=1">all around the world</a>.</p>

  <script src="https://sdk.amazonaws.com/js/aws-sdk-2.1168.0.min.js"></script>
  <script>
    AWS.config.update({
      accessKeyId: '{{.Config.ListingAccessKey}}',
      secretAccessKey: '{{.Config.ListingSecretKey}}',
      region: 'global',
      endpoint: 'https://gateway.storjshare.io',
      s3ForcePathStyle: true
    });

    const s3 = new AWS.S3();

    const bucketName = '{{.Config.Bucket}}';
    const bucketPrefix = '{{.Config.PathPrefix}}';
    const sitePrefix = './';
    const sessionIntervalSeconds = 3*60*60;
    const liveIntervalSeconds = 10*60;
    const imgWidth = 400;
    const refreshInterval = 15000;

    function newImageLoader() {
      var self = {
        loading: new Map(),
        cache: new Map()
      };

      self.load = async function(img, overlay, image) {
        var url = sitePrefix + image;
        var caption = (new Date(timestamp(image))).toLocaleString();
        if (self.cache.has(url)) {
          img.src = self.cache.get(url);
          overlay.textContent = caption;
          return;
        }
        if(self.loading.has(url)) { return; }
        self.loading.set(url, true);
        try {
          var response = await fetch(url);
          if (response.status != 200) {
            throw new Error(response.statusText);
          }
          var data = URL.createObjectURL(await response.blob())
          self.cache.set(url, data);
          img.src = data;
          overlay.textContent = caption;
        } catch(error) {
          console.log(error);
        }
        self.loading.delete(url);
      }

      return self;
    }

    var imageLoader = newImageLoader();

    async function listBucketContents(bucket, prefix, continuationToken=null, entries=[]) {
      const params = {
        Bucket: bucket,
        ContinuationToken: continuationToken,
        Prefix: prefix
      };

      const data = await s3.listObjectsV2(params).promise();
      entries.push(...data.Contents.map(item => {
        if (prefix) {
          return item.Key.slice(prefix.length);
        }
        return item.Key;
      }));

      if (data.IsTruncated) {
        entries = await listBucketContents(bucket, prefix, data.NextContinuationToken, entries);
      } else {
        entries.sort();
      }

      return entries;
    }

    function timestamp(path) {
      var parts = path.split("/");
      if (parts.length != 5) {
        return null;
      }
      var timeparts = parts[4].split(".")[0].split("-");
      return Date.parse(parts[0] + "-" + parts[1] + "-" + parts[2] + "T" +
                        parts[3] + ":" + timeparts[0] + ":" + timeparts[1] + ".000Z");
    }

    function zeroPad(val, length) {
      var rv = "" + val;
      while (rv.length < length) {
        rv = "0" + rv;
      }
      return rv;
    }

    function newMouseHandler(interval, img, overlay) {
      function bisectFind(entries, ts) {
        if (entries.length <= 1) {
          if (entries.length == 0) { return null; }
          return entries[0];
        }
        var mid = Math.floor(entries.length/2);
        if (ts < timestamp(entries[mid])) {
          return bisectFind(entries.slice(0, mid), ts);
        } else {
          return bisectFind(entries.slice(mid), ts);
        }
      }

      return function(ev) {
        var tsWidth = interval.end - interval.beginning;
        var tsMouse = ev.offsetX * tsWidth / imgWidth + interval.beginning;
        var entry = bisectFind(interval.entries, tsMouse);
        if (entry) {
          imageLoader.load(img, overlay, entry);
        }
      };
    }

    async function refresh(bucket, prefix, img, overlay, interval) {
      var now = new Date();
      var subprefix = now.getUTCFullYear() + "/" +
            zeroPad(now.getUTCMonth() + 1, 2) + "/" +
            zeroPad(now.getUTCDate(), 2) + "/" +
            zeroPad(now.getUTCHours(), 2) + "/";
      var entries = await listBucketContents(bucket, prefix + subprefix);
      if (entries.length == 0) { return; }
      var latest = subprefix + entries[entries.length - 1];
      if (interval.entries[interval.entries.length - 1] == latest) {
        return;
      }
      interval.entries.push(latest);
      interval.end = timestamp(latest);
      imageLoader.load(img, overlay, latest);
    }

    async function main() {
      const allEntries = await listBucketContents(bucketName, bucketPrefix);

      var beginning = null;
      var last = null;
      var intervals = [];
      var entries = [];
      allEntries.forEach((item) => {
        var ts = timestamp(item);
        if (!ts) { return; }
        if (!beginning) {
          beginning = ts;
          last = ts;
          entries.push(item);
          return;
        }
        if (ts - sessionIntervalSeconds * 1000 <= last) {
            last = ts;
            entries.push(item);
            return;
        }
        intervals.push({beginning: beginning, end: last, entries: entries});
        beginning = ts;
        last = ts;
        entries = [item];
        return;
      });
      if (beginning) {
        intervals.push({beginning: beginning, end: last, entries: entries})
      }

      function dateOrLive(d) {
        if ((new Date()).getTime() - liveIntervalSeconds * 1000 <= d) {
            return "now";
        }
        return (new Date(d)).toLocaleString();
      }

      var bucketContentList = document.getElementById("bucket-content");
      intervals.reverse().forEach((interval) => {
        var listItem = document.createElement("li");
        var img = document.createElement("img");
        var container = document.createElement("div");
        container.style = "position: relative; width: " + imgWidth + "px;";
        var overlay = document.createElement("div");
        overlay.style = "font-size: smaller; " +
                        "color: green; " +
                        "position: absolute; " +
                        "bottom: 8pt; right: 16pt;";
        imageLoader.load(img, overlay, interval.entries[interval.entries.length-1]);
        img.width = imgWidth;
        img.onmousemove = newMouseHandler(interval, img, overlay);
        var text = document.createElement("p");
        text.textContent = "" + (new Date(interval.beginning)).toLocaleString() + " to " + dateOrLive(interval.end);
        listItem.appendChild(text);
        listItem.appendChild(container);
        container.appendChild(img);
        container.appendChild(overlay);
        bucketContentList.appendChild(listItem);
        if (dateOrLive(interval.end) == "now") {
          function tick() {
            refresh(bucketName, bucketPrefix, img, overlay, interval);
          }
          setInterval(tick, refreshInterval);
        }
      });
    }
  </script>
</body>
</html>
`))
